# Generated by Django 4.0.4 on 2022-04-26 17:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Valid phone no. format: '+977 9845454545' or '9845454545'", regex='(?:\\+977[- ])?9\\d{1}-?\\d{8}(?!\\d)')])),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120, unique=True)),
                ('location', models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Freelance', 'Freelance'), ('Hybrid', 'Hybrid')], db_index=True, default='Onsite', max_length=120)),
                ('type', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime')], db_index=True, default='Fulltime', max_length=25)),
                ('role', models.CharField(choices=[('Project-Manager', 'Project-Manager'), ('Team-Lead', 'Team-Lead'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Quality-Assurance', 'Quality-Assurance')], db_index=True, default='Developer', max_length=25)),
                ('schedule', models.CharField(choices=[('10:00 AM - 05:00 PM', '10:00 AM - 05:00 PM'), ('11:00 AM - 05:00 PM', '11:00 AM - 05:00 PM'), ('07:00 AM - 03:00 PM', '07:00 AM - 03:00 PM'), ('08:00 PM - 05:00 AM', '08:00 PM - 05:00 AM')], default='10:00 AM - 05:00 PM', max_length=22)),
                ('vaccancy', models.IntegerField(default=1)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app.company')),
            ],
        ),
    ]
